DROP TABLE IF EXISTS `ly_site_theme`;
DROP TABLE IF EXISTS `ly_site_category`;
DROP TABLE IF EXISTS `ly_site_article`;
DROP TABLE IF EXISTS `ly_site_flink`;
DROP TABLE IF EXISTS `ly_site_slider`;
DROP TABLE IF EXISTS `ly_site_liuyan`;
DROP TABLE IF EXISTS `ly_site_form`;
DROP TABLE IF EXISTS `ly_site_field`;
DROP TABLE IF EXISTS `ly_site_data`;
